[2025-06-14T21:15:24.744+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_example.extract manual__2025-06-14T21:15:22.005478+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
